apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh-demo
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/rhdh-demo/overlays/development
    repoURL: https://github.com/flacatus/rhdh-qe-demo-gitops
    targetRevision: main
  destination:
    namespace: rhtap
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
